name: Copy file
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List
        run: |
          ls
          
